// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuxlI1t59AHHzV4ZL21vtKBFuBFg96WEg',
    appId: '1:446212635068:web:690b68edebdc289bf1d3b9',
    messagingSenderId: '446212635068',
    projectId: 'scoting-app',
    authDomain: 'scoting-app.firebaseapp.com',
    storageBucket: 'scoting-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOvvFTty8FvBCQF8JG_W5VHuqoKpJRJYo',
    appId: '1:446212635068:android:3aafc6268e50a460f1d3b9',
    messagingSenderId: '446212635068',
    projectId: 'scoting-app',
    storageBucket: 'scoting-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd30P3W_ECpc4RSruEKt17rzc6kDdxXPQ',
    appId: '1:446212635068:ios:59655b601355dbe9f1d3b9',
    messagingSenderId: '446212635068',
    projectId: 'scoting-app',
    storageBucket: 'scoting-app.firebasestorage.app',
    iosBundleId: 'com.example.scoutingQrMaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd30P3W_ECpc4RSruEKt17rzc6kDdxXPQ',
    appId: '1:446212635068:ios:59655b601355dbe9f1d3b9',
    messagingSenderId: '446212635068',
    projectId: 'scoting-app',
    storageBucket: 'scoting-app.firebasestorage.app',
    iosBundleId: 'com.example.scoutingQrMaker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuxlI1t59AHHzV4ZL21vtKBFuBFg96WEg',
    appId: '1:446212635068:web:817c48a2f4b65975f1d3b9',
    messagingSenderId: '446212635068',
    projectId: 'scoting-app',
    authDomain: 'scoting-app.firebaseapp.com',
    storageBucket: 'scoting-app.firebasestorage.app',
  );
}
